### ISSUE TITLE
Failure has occurred while loading a type.

### ISSUE THREAD

**Issue by Nyashers** [Madonox/ScaledLoot#1]
[Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.
Stack trace:
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<DepositItemsDesk::SellItemsOnServer>?937074312(DepositItemsDesk)

**Comment by Madonox** [comment]
I'm working on it right now, should be fixed within a few hours.

**Comment by Madonox** [comment]
Alright.  Issue's fixed on my end, I'll be pushing out a patch in a few minutes.
Turns out I was compiling with the wrong version.
