### ISSUE TITLE
Compatibility with SellMyScrap

### ISSUE THREAD

**Issue by Rimesrea** [Madonox/ScaledLoot#2]
Would it be possible to have it be compatible with SellMyScrap mod or is it something that the SellMyScrap mod author needs to do insead?

I tried using **sell quota** with this mod and it oversold to 73.5k value instead of 14.8k. 

![image](https://github.com/Madonox/ScaledLoot/assets/164140051/7a82599b-d184-4c07-9fc6-82f49c1c49ca)

I really like this mod idea and hopefully will be able to use it in the future.

**Comment by Madonox** [comment]
Hello!  Interesting issue you've reported here.  I'm reading through the `SellMyScrap` mod source code right now, and I think it might be both, as the mod uses some odd methods to sell scrap.  While this one isn't 100% on me, I'll look into adding more sanity checks to improve compatibility with this mod, and mods like it.  I'll be leaving the issue open for now, until I reach a conclusion as to what I'll do.

**Comment by Madonox** [comment]
Alright, after reading through the code, I've found out the issue.  The `SellMyScrap` mod goes off of scrap in the ship's raw value, which my mod only changes when sold, so the `SellMyScrap` mod doesn't consider the scale factor.  I will be adding a patch for this in the next update, which will cause scrap to be scaled when generated.
